// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { IOsShortcut } from '../models';
/**
 * IOSShortcutApi - axios parameter creator
 * @export
 */
export const IOSShortcutApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getShortcutApiV1IosShortcutShortcutGet: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/ios_shortcut/shortcut`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getShortcutApiV1IosShortcutShortcutGet_1: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/v1/ios_shortcut/shortcut`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IOSShortcutApi - functional programming interface
 * @export
 */
export const IOSShortcutApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getShortcutApiV1IosShortcutShortcutGet(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IOsShortcut>> {
            const localVarAxiosArgs = await IOSShortcutApiAxiosParamCreator(configuration).getShortcutApiV1IosShortcutShortcutGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getShortcutApiV1IosShortcutShortcutGet_1(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<IOsShortcut>> {
            const localVarAxiosArgs = await IOSShortcutApiAxiosParamCreator(configuration).getShortcutApiV1IosShortcutShortcutGet_1(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * IOSShortcutApi - factory interface
 * @export
 */
export const IOSShortcutApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getShortcutApiV1IosShortcutShortcutGet(options?: any): AxiosPromise<IOsShortcut> {
            return IOSShortcutApiFp(configuration).getShortcutApiV1IosShortcutShortcutGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getShortcutApiV1IosShortcutShortcutGet_1(options?: any): AxiosPromise<IOsShortcut> {
            return IOSShortcutApiFp(configuration).getShortcutApiV1IosShortcutShortcutGet_1(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IOSShortcutApi - interface
 * @export
 * @interface IOSShortcutApi
 */
export interface IOSShortcutApiInterface {
    /**
     * 
     * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IOSShortcutApiInterface
     */
    getShortcutApiV1IosShortcutShortcutGet(options?: any): AxiosPromise<IOsShortcut>;

    /**
     * 
     * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IOSShortcutApiInterface
     */
    getShortcutApiV1IosShortcutShortcutGet_1(options?: any): AxiosPromise<IOsShortcut>;

}

/**
 * IOSShortcutApi - object-oriented interface
 * @export
 * @class IOSShortcutApi
 * @extends {BaseAPI}
 */
export class IOSShortcutApi extends BaseAPI implements IOSShortcutApiInterface {
    /**
     * 
     * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IOSShortcutApi
     */
    public getShortcutApiV1IosShortcutShortcutGet(options?: any) {
        return IOSShortcutApiFp(this.configuration).getShortcutApiV1IosShortcutShortcutGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 用于iOS快捷指令的版本更新信息/Version update information for iOS shortcuts
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IOSShortcutApi
     */
    public getShortcutApiV1IosShortcutShortcutGet_1(options?: any) {
        return IOSShortcutApiFp(this.configuration).getShortcutApiV1IosShortcutShortcutGet_1(options).then((request) => request(this.axios, this.basePath));
    }

}
