// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { HttpValidationError } from '../models';
// @ts-ignore
import { ResponseModel } from '../models';
/**
 * ToutiaoWebAPIApi - axios parameter creator
 * @export
 */
export const ToutiaoWebAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleInfoApiV1ToutiaoWebGetArticleInfoGet: async (awemeId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'awemeId' is not null or undefined
            if (awemeId === null || awemeId === undefined) {
                throw new RequiredError('awemeId','Required parameter awemeId was null or undefined when calling getArticleInfoApiV1ToutiaoWebGetArticleInfoGet.');
            }
            const localVarPath = `/api/v1/toutiao/web/get_article_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (awemeId !== undefined) {
                localVarQueryParameter['aweme_id'] = awemeId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_1: async (awemeId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'awemeId' is not null or undefined
            if (awemeId === null || awemeId === undefined) {
                throw new RequiredError('awemeId','Required parameter awemeId was null or undefined when calling getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_1.');
            }
            const localVarPath = `/api/v1/toutiao/web/get_article_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (awemeId !== undefined) {
                localVarQueryParameter['aweme_id'] = awemeId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoInfoApiV1ToutiaoWebGetVideoInfoGet: async (awemeId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'awemeId' is not null or undefined
            if (awemeId === null || awemeId === undefined) {
                throw new RequiredError('awemeId','Required parameter awemeId was null or undefined when calling getVideoInfoApiV1ToutiaoWebGetVideoInfoGet.');
            }
            const localVarPath = `/api/v1/toutiao/web/get_video_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (awemeId !== undefined) {
                localVarQueryParameter['aweme_id'] = awemeId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_2: async (awemeId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'awemeId' is not null or undefined
            if (awemeId === null || awemeId === undefined) {
                throw new RequiredError('awemeId','Required parameter awemeId was null or undefined when calling getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_2.');
            }
            const localVarPath = `/api/v1/toutiao/web/get_video_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (awemeId !== undefined) {
                localVarQueryParameter['aweme_id'] = awemeId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ToutiaoWebAPIApi - functional programming interface
 * @export
 */
export const ToutiaoWebAPIApiFp = function(configuration?: Configuration) {
    return {
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getArticleInfoApiV1ToutiaoWebGetArticleInfoGet(awemeId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoWebAPIApiAxiosParamCreator(configuration).getArticleInfoApiV1ToutiaoWebGetArticleInfoGet(awemeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_1(awemeId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoWebAPIApiAxiosParamCreator(configuration).getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_1(awemeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVideoInfoApiV1ToutiaoWebGetVideoInfoGet(awemeId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoWebAPIApiAxiosParamCreator(configuration).getVideoInfoApiV1ToutiaoWebGetVideoInfoGet(awemeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_2(awemeId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoWebAPIApiAxiosParamCreator(configuration).getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_2(awemeId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ToutiaoWebAPIApi - factory interface
 * @export
 */
export const ToutiaoWebAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleInfoApiV1ToutiaoWebGetArticleInfoGet(awemeId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoWebAPIApiFp(configuration).getArticleInfoApiV1ToutiaoWebGetArticleInfoGet(awemeId, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_1(awemeId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoWebAPIApiFp(configuration).getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_1(awemeId, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoInfoApiV1ToutiaoWebGetVideoInfoGet(awemeId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoWebAPIApiFp(configuration).getVideoInfoApiV1ToutiaoWebGetVideoInfoGet(awemeId, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} awemeId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_2(awemeId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoWebAPIApiFp(configuration).getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_2(awemeId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ToutiaoWebAPIApi - interface
 * @export
 * @interface ToutiaoWebAPIApi
 */
export interface ToutiaoWebAPIApiInterface {
    /**
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
     * @summary 获取指定文章的信息/Get information of specified article
     * @param {string} awemeId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoWebAPIApiInterface
     */
    getArticleInfoApiV1ToutiaoWebGetArticleInfoGet(awemeId: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
     * @summary 获取指定文章的信息/Get information of specified article
     * @param {string} awemeId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoWebAPIApiInterface
     */
    getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_1(awemeId: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
     * @summary 获取指定视频的信息/Get information of specified video
     * @param {string} awemeId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoWebAPIApiInterface
     */
    getVideoInfoApiV1ToutiaoWebGetVideoInfoGet(awemeId: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
     * @summary 获取指定视频的信息/Get information of specified video
     * @param {string} awemeId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoWebAPIApiInterface
     */
    getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_2(awemeId: string, options?: any): AxiosPromise<ResponseModel>;

}

/**
 * ToutiaoWebAPIApi - object-oriented interface
 * @export
 * @class ToutiaoWebAPIApi
 * @extends {BaseAPI}
 */
export class ToutiaoWebAPIApi extends BaseAPI implements ToutiaoWebAPIApiInterface {
    /**
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
     * @summary 获取指定文章的信息/Get information of specified article
     * @param {string} awemeId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoWebAPIApi
     */
    public getArticleInfoApiV1ToutiaoWebGetArticleInfoGet(awemeId: string, options?: any) {
        return ToutiaoWebAPIApiFp(this.configuration).getArticleInfoApiV1ToutiaoWebGetArticleInfoGet(awemeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] aweme_id = \"7450114952884503059\"
     * @summary 获取指定文章的信息/Get information of specified article
     * @param {string} awemeId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoWebAPIApi
     */
    public getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_1(awemeId: string, options?: any) {
        return ToutiaoWebAPIApiFp(this.configuration).getArticleInfoApiV1ToutiaoWebGetArticleInfoGet_1(awemeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
     * @summary 获取指定视频的信息/Get information of specified video
     * @param {string} awemeId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoWebAPIApi
     */
    public getVideoInfoApiV1ToutiaoWebGetVideoInfoGet(awemeId: string, options?: any) {
        return ToutiaoWebAPIApiFp(this.configuration).getVideoInfoApiV1ToutiaoWebGetVideoInfoGet(awemeId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - aweme_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - item_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] aweme_id = \"7431543350882206242\"
     * @summary 获取指定视频的信息/Get information of specified video
     * @param {string} awemeId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoWebAPIApi
     */
    public getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_2(awemeId: string, options?: any) {
        return ToutiaoWebAPIApiFp(this.configuration).getVideoInfoApiV1ToutiaoWebGetVideoInfoGet_2(awemeId, options).then((request) => request(this.axios, this.basePath));
    }

}
