// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as globalImportUrl from 'url';
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { HttpValidationError } from '../models';
// @ts-ignore
import { ResponseModel } from '../models';
/**
 * ToutiaoAppAPIApi - axios parameter creator
 * @export
 */
export const ToutiaoAppAPIApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleInfoApiV1ToutiaoAppGetArticleInfoGet: async (groupId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            if (groupId === null || groupId === undefined) {
                throw new RequiredError('groupId','Required parameter groupId was null or undefined when calling getArticleInfoApiV1ToutiaoAppGetArticleInfoGet.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_article_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (groupId !== undefined) {
                localVarQueryParameter['group_id'] = groupId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_1: async (groupId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            if (groupId === null || groupId === undefined) {
                throw new RequiredError('groupId','Required parameter groupId was null or undefined when calling getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_1.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_article_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (groupId !== undefined) {
                localVarQueryParameter['group_id'] = groupId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
         * @summary 获取指定作品的评论/Get comments of specified post
         * @param {string} groupId 作品ID/Post ID
         * @param {string} offset 偏移量/Offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommentsApiV1ToutiaoAppGetCommentsGet: async (groupId: string, offset: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            if (groupId === null || groupId === undefined) {
                throw new RequiredError('groupId','Required parameter groupId was null or undefined when calling getCommentsApiV1ToutiaoAppGetCommentsGet.');
            }
            // verify required parameter 'offset' is not null or undefined
            if (offset === null || offset === undefined) {
                throw new RequiredError('offset','Required parameter offset was null or undefined when calling getCommentsApiV1ToutiaoAppGetCommentsGet.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_comments`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (groupId !== undefined) {
                localVarQueryParameter['group_id'] = groupId;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
         * @summary 获取指定作品的评论/Get comments of specified post
         * @param {string} groupId 作品ID/Post ID
         * @param {string} offset 偏移量/Offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommentsApiV1ToutiaoAppGetCommentsGet_2: async (groupId: string, offset: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            if (groupId === null || groupId === undefined) {
                throw new RequiredError('groupId','Required parameter groupId was null or undefined when calling getCommentsApiV1ToutiaoAppGetCommentsGet_2.');
            }
            // verify required parameter 'offset' is not null or undefined
            if (offset === null || offset === undefined) {
                throw new RequiredError('offset','Required parameter offset was null or undefined when calling getCommentsApiV1ToutiaoAppGetCommentsGet_2.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_comments`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (groupId !== undefined) {
                localVarQueryParameter['group_id'] = groupId;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
         * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
         * @param {string} userProfileUrl 用户主页链接/User profile URL
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserIdApiV1ToutiaoAppGetUserIdGet: async (userProfileUrl: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'userProfileUrl' is not null or undefined
            if (userProfileUrl === null || userProfileUrl === undefined) {
                throw new RequiredError('userProfileUrl','Required parameter userProfileUrl was null or undefined when calling getUserIdApiV1ToutiaoAppGetUserIdGet.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_user_id`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (userProfileUrl !== undefined) {
                localVarQueryParameter['user_profile_url'] = userProfileUrl;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
         * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
         * @param {string} userProfileUrl 用户主页链接/User profile URL
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserIdApiV1ToutiaoAppGetUserIdGet_3: async (userProfileUrl: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'userProfileUrl' is not null or undefined
            if (userProfileUrl === null || userProfileUrl === undefined) {
                throw new RequiredError('userProfileUrl','Required parameter userProfileUrl was null or undefined when calling getUserIdApiV1ToutiaoAppGetUserIdGet_3.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_user_id`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (userProfileUrl !== undefined) {
                localVarQueryParameter['user_profile_url'] = userProfileUrl;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
         * @summary 获取指定用户的信息/Get information of specified user
         * @param {string} userId 用户ID/User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfoApiV1ToutiaoAppGetUserInfoGet: async (userId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling getUserInfoApiV1ToutiaoAppGetUserInfoGet.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_user_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
         * @summary 获取指定用户的信息/Get information of specified user
         * @param {string} userId 用户ID/User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfoApiV1ToutiaoAppGetUserInfoGet_4: async (userId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            if (userId === null || userId === undefined) {
                throw new RequiredError('userId','Required parameter userId was null or undefined when calling getUserInfoApiV1ToutiaoAppGetUserInfoGet_4.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_user_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (userId !== undefined) {
                localVarQueryParameter['user_id'] = userId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoInfoApiV1ToutiaoAppGetVideoInfoGet: async (groupId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            if (groupId === null || groupId === undefined) {
                throw new RequiredError('groupId','Required parameter groupId was null or undefined when calling getVideoInfoApiV1ToutiaoAppGetVideoInfoGet.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_video_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (groupId !== undefined) {
                localVarQueryParameter['group_id'] = groupId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_5: async (groupId: string, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'groupId' is not null or undefined
            if (groupId === null || groupId === undefined) {
                throw new RequiredError('groupId','Required parameter groupId was null or undefined when calling getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_5.');
            }
            const localVarPath = `/api/v1/toutiao/app/get_video_info`;
            const localVarUrlObj = globalImportUrl.parse(localVarPath, true);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? configuration.accessToken()
                    : configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (groupId !== undefined) {
                localVarQueryParameter['group_id'] = groupId;
            }


    
            localVarUrlObj.query = {...localVarUrlObj.query, ...localVarQueryParameter, ...options.query};
            // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
            delete localVarUrlObj.search;
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: globalImportUrl.format(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ToutiaoAppAPIApi - functional programming interface
 * @export
 */
export const ToutiaoAppAPIApiFp = function(configuration?: Configuration) {
    return {
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getArticleInfoApiV1ToutiaoAppGetArticleInfoGet(groupId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getArticleInfoApiV1ToutiaoAppGetArticleInfoGet(groupId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_1(groupId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_1(groupId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
         * @summary 获取指定作品的评论/Get comments of specified post
         * @param {string} groupId 作品ID/Post ID
         * @param {string} offset 偏移量/Offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCommentsApiV1ToutiaoAppGetCommentsGet(groupId: string, offset: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getCommentsApiV1ToutiaoAppGetCommentsGet(groupId, offset, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
         * @summary 获取指定作品的评论/Get comments of specified post
         * @param {string} groupId 作品ID/Post ID
         * @param {string} offset 偏移量/Offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCommentsApiV1ToutiaoAppGetCommentsGet_2(groupId: string, offset: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getCommentsApiV1ToutiaoAppGetCommentsGet_2(groupId, offset, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
         * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
         * @param {string} userProfileUrl 用户主页链接/User profile URL
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserIdApiV1ToutiaoAppGetUserIdGet(userProfileUrl: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getUserIdApiV1ToutiaoAppGetUserIdGet(userProfileUrl, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
         * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
         * @param {string} userProfileUrl 用户主页链接/User profile URL
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserIdApiV1ToutiaoAppGetUserIdGet_3(userProfileUrl: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getUserIdApiV1ToutiaoAppGetUserIdGet_3(userProfileUrl, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
         * @summary 获取指定用户的信息/Get information of specified user
         * @param {string} userId 用户ID/User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInfoApiV1ToutiaoAppGetUserInfoGet(userId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getUserInfoApiV1ToutiaoAppGetUserInfoGet(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
         * @summary 获取指定用户的信息/Get information of specified user
         * @param {string} userId 用户ID/User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInfoApiV1ToutiaoAppGetUserInfoGet_4(userId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getUserInfoApiV1ToutiaoAppGetUserInfoGet_4(userId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVideoInfoApiV1ToutiaoAppGetVideoInfoGet(groupId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getVideoInfoApiV1ToutiaoAppGetVideoInfoGet(groupId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_5(groupId: string, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResponseModel>> {
            const localVarAxiosArgs = await ToutiaoAppAPIApiAxiosParamCreator(configuration).getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_5(groupId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ToutiaoAppAPIApi - factory interface
 * @export
 */
export const ToutiaoAppAPIApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleInfoApiV1ToutiaoAppGetArticleInfoGet(groupId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getArticleInfoApiV1ToutiaoAppGetArticleInfoGet(groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
         * @summary 获取指定文章的信息/Get information of specified article
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_1(groupId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_1(groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
         * @summary 获取指定作品的评论/Get comments of specified post
         * @param {string} groupId 作品ID/Post ID
         * @param {string} offset 偏移量/Offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommentsApiV1ToutiaoAppGetCommentsGet(groupId: string, offset: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getCommentsApiV1ToutiaoAppGetCommentsGet(groupId, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
         * @summary 获取指定作品的评论/Get comments of specified post
         * @param {string} groupId 作品ID/Post ID
         * @param {string} offset 偏移量/Offset
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommentsApiV1ToutiaoAppGetCommentsGet_2(groupId: string, offset: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getCommentsApiV1ToutiaoAppGetCommentsGet_2(groupId, offset, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
         * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
         * @param {string} userProfileUrl 用户主页链接/User profile URL
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserIdApiV1ToutiaoAppGetUserIdGet(userProfileUrl: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getUserIdApiV1ToutiaoAppGetUserIdGet(userProfileUrl, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
         * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
         * @param {string} userProfileUrl 用户主页链接/User profile URL
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserIdApiV1ToutiaoAppGetUserIdGet_3(userProfileUrl: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getUserIdApiV1ToutiaoAppGetUserIdGet_3(userProfileUrl, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
         * @summary 获取指定用户的信息/Get information of specified user
         * @param {string} userId 用户ID/User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfoApiV1ToutiaoAppGetUserInfoGet(userId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getUserInfoApiV1ToutiaoAppGetUserInfoGet(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
         * @summary 获取指定用户的信息/Get information of specified user
         * @param {string} userId 用户ID/User ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfoApiV1ToutiaoAppGetUserInfoGet_4(userId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getUserInfoApiV1ToutiaoAppGetUserInfoGet_4(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoInfoApiV1ToutiaoAppGetVideoInfoGet(groupId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getVideoInfoApiV1ToutiaoAppGetVideoInfoGet(groupId, options).then((request) => request(axios, basePath));
        },
        /**
         * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
         * @summary 获取指定视频的信息/Get information of specified video
         * @param {string} groupId 作品ID/Post ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_5(groupId: string, options?: any): AxiosPromise<ResponseModel> {
            return ToutiaoAppAPIApiFp(configuration).getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_5(groupId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ToutiaoAppAPIApi - interface
 * @export
 * @interface ToutiaoAppAPIApi
 */
export interface ToutiaoAppAPIApiInterface {
    /**
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
     * @summary 获取指定文章的信息/Get information of specified article
     * @param {string} groupId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getArticleInfoApiV1ToutiaoAppGetArticleInfoGet(groupId: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
     * @summary 获取指定文章的信息/Get information of specified article
     * @param {string} groupId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_1(groupId: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
     * @summary 获取指定作品的评论/Get comments of specified post
     * @param {string} groupId 作品ID/Post ID
     * @param {string} offset 偏移量/Offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getCommentsApiV1ToutiaoAppGetCommentsGet(groupId: string, offset: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
     * @summary 获取指定作品的评论/Get comments of specified post
     * @param {string} groupId 作品ID/Post ID
     * @param {string} offset 偏移量/Offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getCommentsApiV1ToutiaoAppGetCommentsGet_2(groupId: string, offset: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
     * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
     * @param {string} userProfileUrl 用户主页链接/User profile URL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getUserIdApiV1ToutiaoAppGetUserIdGet(userProfileUrl: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
     * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
     * @param {string} userProfileUrl 用户主页链接/User profile URL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getUserIdApiV1ToutiaoAppGetUserIdGet_3(userProfileUrl: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
     * @summary 获取指定用户的信息/Get information of specified user
     * @param {string} userId 用户ID/User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getUserInfoApiV1ToutiaoAppGetUserInfoGet(userId: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
     * @summary 获取指定用户的信息/Get information of specified user
     * @param {string} userId 用户ID/User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getUserInfoApiV1ToutiaoAppGetUserInfoGet_4(userId: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
     * @summary 获取指定视频的信息/Get information of specified video
     * @param {string} groupId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getVideoInfoApiV1ToutiaoAppGetVideoInfoGet(groupId: string, options?: any): AxiosPromise<ResponseModel>;

    /**
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
     * @summary 获取指定视频的信息/Get information of specified video
     * @param {string} groupId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApiInterface
     */
    getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_5(groupId: string, options?: any): AxiosPromise<ResponseModel>;

}

/**
 * ToutiaoAppAPIApi - object-oriented interface
 * @export
 * @class ToutiaoAppAPIApi
 * @extends {BaseAPI}
 */
export class ToutiaoAppAPIApi extends BaseAPI implements ToutiaoAppAPIApiInterface {
    /**
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
     * @summary 获取指定文章的信息/Get information of specified article
     * @param {string} groupId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getArticleInfoApiV1ToutiaoAppGetArticleInfoGet(groupId: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getArticleInfoApiV1ToutiaoAppGetArticleInfoGet(groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定文章的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/article/7450114952884503059/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/article/7450114952884503059/ ### Return: - Post information  # [示例/Example] group_id = \"7450114952884503059\"
     * @summary 获取指定文章的信息/Get information of specified article
     * @param {string} groupId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_1(groupId: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getArticleInfoApiV1ToutiaoAppGetArticleInfoGet_1(groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
     * @summary 获取指定作品的评论/Get comments of specified post
     * @param {string} groupId 作品ID/Post ID
     * @param {string} offset 偏移量/Offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getCommentsApiV1ToutiaoAppGetCommentsGet(groupId: string, offset: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getCommentsApiV1ToutiaoAppGetCommentsGet(groupId, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定作品的评论 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/i7453372680222523931/ - offset: 偏移量，用于分页，默认为0，然后每次加20 ### 返回: - 评论列表  # [English] ### Purpose: - Get comments of specified post ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/i7453372680222523931/ - offset: Offset, used for pagination, default is 0, then add 20 each time ### Return: - Comment list  # [示例/Example] group_id = \"7453372680222523931\" offset = \"0\"
     * @summary 获取指定作品的评论/Get comments of specified post
     * @param {string} groupId 作品ID/Post ID
     * @param {string} offset 偏移量/Offset
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getCommentsApiV1ToutiaoAppGetCommentsGet_2(groupId: string, offset: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getCommentsApiV1ToutiaoAppGetCommentsGet_2(groupId, offset, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
     * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
     * @param {string} userProfileUrl 用户主页链接/User profile URL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getUserIdApiV1ToutiaoAppGetUserIdGet(userProfileUrl: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getUserIdApiV1ToutiaoAppGetUserIdGet(userProfileUrl, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 从头条用户主页获取用户user_id ### 参数: - user_profile_url: 用户主页链接     - 例如: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### 返回: - 用户ID  # [English] ### Purpose: - Get user_id from user profile ### Parameters: - user_profile_url: User profile URL     - For example: https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/ ### Return: - User ID  # [示例/Example] user_profile_url = \"https://www.toutiao.com/c/user/token/MS4wLjABAAAAwK6echNksY69R8l2vcZudupfhTItbGSGt-8ineO5UaB4L-djqkYDgB6TkAdMvrmW/\"
     * @summary 从头条用户主页获取用户user_id/Get user_id from user profile
     * @param {string} userProfileUrl 用户主页链接/User profile URL
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getUserIdApiV1ToutiaoAppGetUserIdGet_3(userProfileUrl: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getUserIdApiV1ToutiaoAppGetUserIdGet_3(userProfileUrl, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
     * @summary 获取指定用户的信息/Get information of specified user
     * @param {string} userId 用户ID/User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getUserInfoApiV1ToutiaoAppGetUserInfoGet(userId: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getUserInfoApiV1ToutiaoAppGetUserInfoGet(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定用户的信息 ### 参数: - user_id: 用户ID，可以从以下接口获取：     - `/api/v1/toutiao/app/get_user_id` ### 返回: - 用户信息  # [English] ### Purpose: - Get information of specified user ### Parameters: - user_id: User ID, can be obtained from the following API:     - `/api/v1/toutiao/app/get_user_id` ### Return: - User information  # [示例/Example] user_id = \"1352838578180211\"
     * @summary 获取指定用户的信息/Get information of specified user
     * @param {string} userId 用户ID/User ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getUserInfoApiV1ToutiaoAppGetUserInfoGet_4(userId: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getUserInfoApiV1ToutiaoAppGetUserInfoGet_4(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
     * @summary 获取指定视频的信息/Get information of specified video
     * @param {string} groupId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getVideoInfoApiV1ToutiaoAppGetVideoInfoGet(groupId: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getVideoInfoApiV1ToutiaoAppGetVideoInfoGet(groupId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * # [中文] ### 用途: - 获取指定视频的信息 ### 参数: - group_id: 作品ID，可以从链接中获取     - 例如: https://www.toutiao.com/video/7431543350882206242/ ### 返回: - 作品信息  # [English] ### Purpose: - Get information of specified video ### Parameters: - group_id: Post ID, can be obtained from the link     - For example: https://www.toutiao.com/video/7431543350882206242/ ### Return: - Post information  # [示例/Example] group_id = \"7431543350882206242\"
     * @summary 获取指定视频的信息/Get information of specified video
     * @param {string} groupId 作品ID/Post ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ToutiaoAppAPIApi
     */
    public getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_5(groupId: string, options?: any) {
        return ToutiaoAppAPIApiFp(this.configuration).getVideoInfoApiV1ToutiaoAppGetVideoInfoGet_5(groupId, options).then((request) => request(this.axios, this.basePath));
    }

}
