// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ABogusModel
 * @export
 * @interface ABogusModel
 */
export interface ABogusModel {
    /**
     * Url，请求的API URL，需要使用urlencode(url, safe=\'*\')进行编码 | The requested API URL, needs to be encoded using urlencode(url, safe=\'*\')
     * @type {string}
     * @memberof ABogusModel
     */
    url: string;
    /**
     * Data，POST请求API时的载荷数据，需要使用urlencode(data, safe=\'*\')进行编码 | The payload data when requesting the API with POST, needs to be encoded using urlencode(data, safe=\'*\')
     * @type {string}
     * @memberof ABogusModel
     */
    data: string;
    /**
     * User Agent，请求API时的User-Agent | User-Agent when requesting the API
     * @type {string}
     * @memberof ABogusModel
     */
    userAgent: string;
    /**
     * Index 0，加密明文列表的第一个值，无特殊要求，默认为0
     * @type {number}
     * @memberof ABogusModel
     */
    index0?: number;
    /**
     * Index 1，加密明文列表的第一个值，无特殊要求，默认为1
     * @type {number}
     * @memberof ABogusModel
     */
    index1?: number;
    /**
     * Index 2，加密明文列表的第一个值，无特殊要求，默认为14
     * @type {number}
     * @memberof ABogusModel
     */
    index2?: number;
}


