// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';

/**
 * APIKeyData
 * @export
 * @interface ApiKeyData
 */
export interface ApiKeyData {
    /**
     * Api Key Name
     * @type {string}
     * @memberof ApiKeyData
     */
    apiKeyName: string;
    /**
     * Api Key Scopes
     * @type {Array<string>}
     * @memberof ApiKeyData
     */
    apiKeyScopes: Array<string>;
    /**
     * Created At
     * @type {string}
     * @memberof ApiKeyData
     */
    createdAt: string;
    /**
     * Expires At
     * @type {string | Null}
     * @memberof ApiKeyData
     */
    expiresAt: string | Null;
    /**
     * Api Key Status
     * @type {number}
     * @memberof ApiKeyData
     */
    apiKeyStatus: number;
}


