// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Body_fetch_hot_total_hot_word_list_api_v1_douyin_billboard_fetch_hot_total_hot_word_list_post
 * @export
 * @interface BodyFetchHotTotalHotWordListApiV1DouyinBillboardFetchHotTotalHotWordListPost
 */
export interface BodyFetchHotTotalHotWordListApiV1DouyinBillboardFetchHotTotalHotWordListPost {
    /**
     * Page Num，页码
     * @type {number}
     * @memberof BodyFetchHotTotalHotWordListApiV1DouyinBillboardFetchHotTotalHotWordListPost
     */
    pageNum?: number;
    /**
     * Page Size，每页数量
     * @type {number}
     * @memberof BodyFetchHotTotalHotWordListApiV1DouyinBillboardFetchHotTotalHotWordListPost
     */
    pageSize?: number;
    /**
     * Date Window，时间窗口，1 按小时 2 按天
     * @type {number}
     * @memberof BodyFetchHotTotalHotWordListApiV1DouyinBillboardFetchHotTotalHotWordListPost
     */
    dateWindow?: number;
    /**
     * Keyword，搜索关键字
     * @type {string}
     * @memberof BodyFetchHotTotalHotWordListApiV1DouyinBillboardFetchHotTotalHotWordListPost
     */
    keyword?: string;
}


