// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Body_fetch_home_feed_api_v1_tiktok_web_fetch_home_feed_post
 * @export
 * @interface BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost
 */
export interface BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost {
    /**
     * Count，每页数量/Number per page
     * @type {number}
     * @memberof BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost
     */
    count?: number;
    /**
     * Cookie，用户自己的cookie，可选参数，用于接口返回数据的个性化推荐。/ User\'s own cookie, optional parameter, used for personalized recommendations of interface return data.
     * @type {string}
     * @memberof BodyFetchHomeFeedApiV1TiktokWebFetchHomeFeedPost
     */
    cookie?: string;
}


