// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Body_fetch_hot_calendar_list_api_v1_douyin_billboard_fetch_hot_calendar_list_post
 * @export
 * @interface BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost
 */
export interface BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost {
    /**
     * City Code，城市编码，从城市列表获取，空为全部
     * @type {string}
     * @memberof BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost
     */
    cityCode?: string;
    /**
     * Category Code，热点榜分类编码，从热点榜分类获取，空为全部
     * @type {string}
     * @memberof BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost
     */
    categoryCode?: string;
    /**
     * End Date，快照结束时间 格式10位时间戳
     * @type {number}
     * @memberof BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost
     */
    endDate?: number;
    /**
     * Start Date，快照开始时间 格式10位时间戳
     * @type {number}
     * @memberof BodyFetchHotCalendarListApiV1DouyinBillboardFetchHotCalendarListPost
     */
    startDate?: number;
}


