// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Body_fetch_hot_account_list_api_v1_douyin_billboard_fetch_hot_account_list_post
 * @export
 * @interface BodyFetchHotAccountListApiV1DouyinBillboardFetchHotAccountListPost
 */
export interface BodyFetchHotAccountListApiV1DouyinBillboardFetchHotAccountListPost {
    /**
     * Date Window，时间窗口，格式 小时，默认24小时
     * @type {string}
     * @memberof BodyFetchHotAccountListApiV1DouyinBillboardFetchHotAccountListPost
     */
    dateWindow?: string;
    /**
     * Page Num，页码，默认1
     * @type {string}
     * @memberof BodyFetchHotAccountListApiV1DouyinBillboardFetchHotAccountListPost
     */
    pageNum?: string;
    /**
     * Page Size，每页数量，默认10
     * @type {string}
     * @memberof BodyFetchHotAccountListApiV1DouyinBillboardFetchHotAccountListPost
     */
    pageSize?: string;
    /**
     * Query Tag，子级垂类标签，空则为全部，多个标签需传入{\"value\": \"{顶级垂类标签id}\", \"children\": [{\"value\": \"{子级垂类标签id}\"}, {\"value\": \"{子级垂类标签id}\"}]}
     * @type {object}
     * @memberof BodyFetchHotAccountListApiV1DouyinBillboardFetchHotAccountListPost
     */
    queryTag?: object;
}


