// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Body_hcaptcha_api_v1_captcha_hcaptcha_post
 * @export
 * @interface BodyHcaptchaApiV1CaptchaHcaptchaPost
 */
export interface BodyHcaptchaApiV1CaptchaHcaptchaPost {
    /**
     * Sitekey，Sitekey
     * @type {string}
     * @memberof BodyHcaptchaApiV1CaptchaHcaptchaPost
     */
    sitekey: string;
    /**
     * Url，URL
     * @type {string}
     * @memberof BodyHcaptchaApiV1CaptchaHcaptchaPost
     */
    url: string;
    /**
     * Proxy，Proxy
     * @type {object}
     * @memberof BodyHcaptchaApiV1CaptchaHcaptchaPost
     */
    proxy?: object;
}


