// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Body_amazon_captcha_api_v1_captcha_amazon_captcha_post
 * @export
 * @interface BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost
 */
export interface BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost {
    /**
     * App Id，App ID
     * @type {string}
     * @memberof BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost
     */
    appId: string;
    /**
     * Url，URL
     * @type {string}
     * @memberof BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost
     */
    url: string;
    /**
     * Proxy，Proxy
     * @type {object}
     * @memberof BodyAmazonCaptchaApiV1CaptchaAmazonCaptchaPost
     */
    proxy?: object;
}


