// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ChallengePostRequest
 * @export
 * @interface ChallengePostRequest
 */
export interface ChallengePostRequest {
    /**
     * Challenge Id，话题ID/Challenge ID
     * @type {string}
     * @memberof ChallengePostRequest
     */
    challengeId?: string;
    /**
     * Sort Type，排序类型/Sort type
     * @type {number}
     * @memberof ChallengePostRequest
     */
    sortType?: number;
    /**
     * Cursor，游标/Cursor
     * @type {number}
     * @memberof ChallengePostRequest
     */
    cursor?: number;
    /**
     * Count，数量/Count
     * @type {number}
     * @memberof ChallengePostRequest
     */
    count?: number;
    /**
     * Cookie，用户自行提供的Cookie/User provided Cookie
     * @type {string}
     * @memberof ChallengePostRequest
     */
    cookie?: string;
}


