// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GetHomeFeedRequest
 * @export
 * @interface GetHomeFeedRequest
 */
export interface GetHomeFeedRequest {
    /**
     * Feed Type，推荐类型/Feed type
     * @type {string}
     * @memberof GetHomeFeedRequest
     */
    feedType?: string;
    /**
     * Need Filter Image，是否只看图文笔记/Whether to view only image notes
     * @type {boolean}
     * @memberof GetHomeFeedRequest
     */
    needFilterImage?: boolean;
    /**
     * Cookie，用户自行提供的已登录的网页Cookie/User provided logged-in web Cookie
     * @type {string}
     * @memberof GetHomeFeedRequest
     */
    cookie?: string;
    /**
     * Proxy，代理，格式：http://用户名:密码@IP:端口/Proxy, format: http://username:password@IP:port
     * @type {string}
     * @memberof GetHomeFeedRequest
     */
    proxy?: string;
}


