// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * GetNoteInfoV5Request
 * @export
 * @interface GetNoteInfoV5Request
 */
export interface GetNoteInfoV5Request {
    /**
     * Note Id，笔记ID/Note ID
     * @type {string}
     * @memberof GetNoteInfoV5Request
     */
    noteId?: string;
    /**
     * Xsec Token，X-Sec-Token，可以从搜索接口中获取/X-Sec-Token, can be obtained from the search interface
     * @type {string}
     * @memberof GetNoteInfoV5Request
     */
    xsecToken?: string;
    /**
     * Cookie，用户自行提供的已登录的网页Cookie/User provided logged-in web Cookie
     * @type {string}
     * @memberof GetNoteInfoV5Request
     */
    cookie?: string;
    /**
     * Proxy，代理，格式：http://用户名:密码@IP:端口/Proxy, format: http://username:password@IP:port
     * @type {string}
     * @memberof GetNoteInfoV5Request
     */
    proxy?: string;
}


