// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * iOS_Shortcut
 * @export
 * @interface IOsShortcut
 */
export interface IOsShortcut {
    /**
     * Version
     * @type {string}
     * @memberof IOsShortcut
     */
    version: string;
    /**
     * Update
     * @type {string}
     * @memberof IOsShortcut
     */
    update: string;
    /**
     * Link
     * @type {string}
     * @memberof IOsShortcut
     */
    link: string;
    /**
     * Link En
     * @type {string}
     * @memberof IOsShortcut
     */
    linkEn: string;
    /**
     * Note
     * @type {string}
     * @memberof IOsShortcut
     */
    note: string;
    /**
     * Note En
     * @type {string}
     * @memberof IOsShortcut
     */
    noteEn: string;
}


