// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * ReplyCommentRequest
 * @export
 * @interface ReplyCommentRequest
 */
export interface ReplyCommentRequest {
    /**
     * AKA Video ID，Video ID, which can be obtained from the sharing link, for example: https://www.tiktok.com/@username/video/7419966340443819295
     * @type {string}
     * @memberof ReplyCommentRequest
     */
    awemeId?: string;
    /**
     * Reply Comment ID AKA CID，Comment ID, which can be obtained from the comment data of the specified video.
     * @type {string}
     * @memberof ReplyCommentRequest
     */
    replyId?: string;
    /**
     * Comment Content，Comment content, TikTok comment content needs to comply with the specifications, do not contain illegal keywords, otherwise, even if the request is successful, it will be judged as spam comments by the system and will not be displayed.
     * @type {string}
     * @memberof ReplyCommentRequest
     */
    text?: string;
    /**
     * User Cookie，User Cookie, you can log in to your TikTok account in the browser and then copy the Cookie information, please use URL-encoded Cookie string when submitting.
     * @type {string}
     * @memberof ReplyCommentRequest
     */
    cookie?: string;
    /**
     * Device ID，Device id, optional, if not filled in, it will be automatically generated, if you need to customize the device id, please use the device information interface to get the device id.
     * @type {string}
     * @memberof ReplyCommentRequest
     */
    deviceId?: string;
    /**
     * Device Install ID，Device install id, optional, if not filled in, it will be automatically generated, if you need to customize the device iid, please use the device information interface to get the device iid.
     * @type {string}
     * @memberof ReplyCommentRequest
     */
    iid?: string;
    /**
     * Proxy IP，Proxy IP, optional, if not filled in, it will be automatically generated, if you need to customize the proxy IP, please use the proxy IP interface to get the proxy IP.
     * @type {string}
     * @memberof ReplyCommentRequest
     */
    proxy?: string;
}


