// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ResponseModel
 * @export
 * @interface ResponseModel
 */
export interface ResponseModel {
    /**
     * Code，HTTP status code | HTTP状态码
     * @type {number}
     * @memberof ResponseModel
     */
    code?: number;
    /**
     * Router，The endpoint that generated this response | 生成此响应的端点
     * @type {string}
     * @memberof ResponseModel
     */
    router?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseModel
     */
    params?: string;
    /**
     * Data，The response data | 响应数据
     * @type {string | Null}
     * @memberof ResponseModel
     */
    data?: string | null;
}


