// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * SearchChallengeRequest
 * @export
 * @interface SearchChallengeRequest
 */
export interface SearchChallengeRequest {
    /**
     * Keyword，搜索关键词/Search keyword
     * @type {string}
     * @memberof SearchChallengeRequest
     */
    keyword?: string;
    /**
     * Cursor，游标/Cursor
     * @type {number}
     * @memberof SearchChallengeRequest
     */
    cursor?: number;
    /**
     * Count，数量/Count
     * @type {number}
     * @memberof SearchChallengeRequest
     */
    count?: number;
    /**
     * Cookie，用户自行提供的Cookie/User provided Cookie
     * @type {string}
     * @memberof SearchChallengeRequest
     */
    cookie?: string;
}


