// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TikTok_APP_V3_Home_Feed
 * @export
 * @interface TikTokAppV3HomeFeed
 */
export interface TikTokAppV3HomeFeed {
    /**
     * Cookie，用户自己的cookie，可选参数，用于接口返回数据的个性化推荐。/ User\'s own cookie, optional parameter, used for personalized recommendations of interface return data.
     * @type {string}
     * @memberof TikTokAppV3HomeFeed
     */
    cookie?: string;
}


