// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ModeEnum } from './mode-enum';

/**
 * TikTok_APP_Login_Encrypt_Decrypt_Request
 * @export
 * @interface TikTokAppLoginEncryptDecryptRequest
 */
export interface TikTokAppLoginEncryptDecryptRequest {
    /**
     * Username，Plaintext or encrypted username
     * @type {string}
     * @memberof TikTokAppLoginEncryptDecryptRequest
     */
    username?: string;
    /**
     * Password，Plaintext or encrypted password
     * @type {string}
     * @memberof TikTokAppLoginEncryptDecryptRequest
     */
    password?: string;
    /**
     * Encrypt or decrypt the input string
     * @type {ModeEnum}
     * @memberof TikTokAppLoginEncryptDecryptRequest
     */
    mode?: ModeEnum;
}


