// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TikTok_APP_V3_Content_Translate
 * @export
 * @interface TikTokAppV3ContentTranslate
 */
export interface TikTokAppV3ContentTranslate {
    /**
     * Trg Lang，目标语言ISO639-1代码，例如：zh-Hans/ Target language ISO639-1 code, e.g. zh-Hans
     * @type {string}
     * @memberof TikTokAppV3ContentTranslate
     */
    trgLang?: string;
    /**
     * Src Content，源语言内容，也就是需要翻译的内容/ Source language content, i.e. the content to be translated
     * @type {string}
     * @memberof TikTokAppV3ContentTranslate
     */
    srcContent?: string;
}


