// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * TikTok_APP_Encrypt_Request
 * @export
 * @interface TikTokAppEncryptRequest
 */
export interface TikTokAppEncryptRequest {
    /**
     * Url，需要加密的URL/URL to be encrypted
     * @type {string}
     * @memberof TikTokAppEncryptRequest
     */
    url?: string;
    /**
     * Data，如果有POST请求，请填写POST请求的数据参与加密计算/If there is a POST request, please fill in the data of the POST request to participate in the encryption calculation
     * @type {string}
     * @memberof TikTokAppEncryptRequest
     */
    data?: string;
    /**
     * Device Info，设备信息，可选参数，如果不填写则使用默认设备信息/Device information, optional parameter, if not filled in, the default device information is used
     * @type {object}
     * @memberof TikTokAppEncryptRequest
     */
    deviceInfo?: object;
}


