// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * XBogusModel
 * @export
 * @interface XBogusModel
 */
export interface XBogusModel {
    /**
     * Url，请求的API URL，不需要进行编码 | The requested API URL, no need to encode
     * @type {string}
     * @memberof XBogusModel
     */
    url: string;
    /**
     * User Agent，请求API时的User-Agent | User-Agent when requesting the API
     * @type {string}
     * @memberof XBogusModel
     */
    userAgent: string;
}


