// tslint:disable
/**
 * TikHub Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * XhsWebSignRequestModel
 * @export
 * @interface XhsWebSignRequestModel
 */
export interface XhsWebSignRequestModel {
    /**
     * Path，请求接口的路径/Request API path
     * @type {string}
     * @memberof XhsWebSignRequestModel
     */
    path?: string;
    /**
     * Data，请求API的荷载数据/Payload data of request API
     * @type {object}
     * @memberof XhsWebSignRequestModel
     */
    data?: object;
    /**
     * Cookie，请求接口的Cookie/Request API cookie
     * @type {string}
     * @memberof XhsWebSignRequestModel
     */
    cookie?: string;
}


